export const SET_AUCTIONS = "SET_AUCTIONS";
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
export const SET_AVAILABLE_CATEGORIES = "SET_AVAILABLE_CATEGORIES";
export const SET_TIMER = "SET_TIMER";
export const SET_AUCTION_LOADING = "SET_AUCTION_LOADING";
